[package]
license = "MIT"
authors = ["Hystersis AI"]
edition.workspace = true
name = "hystersis-agent-lifecycle"
version = "0.1.0"

[dependencies]
async-trait = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
